/* ==========================================================================
 * Catálogo de leiautes dos arquivos de remessa do SIM (TCE-CE)
 * --------------------------------------------------------------------------
 * Os nomes dos campos foram inferidos a partir da análise dos arquivos de
 * uma competência real (145202312P) e cruzamento com o relatório FUNDEB.
 * O manual oficial do SIM não pôde ser consultado durante a construção.
 *
 * Confiança de cada campo (c):
 *   'certeza'  - confirmado por cruzamento entre arquivos / relatório
 *   'provavel' - inferência forte a partir do conteúdo
 *   'chute'    - nome descritivo provisório; conferir no Manual do SIM
 *
 * Tipos (t): txt | num | dat (AAAAMMDD) | cmp (AAAAMM)
 * ========================================================================== */
(function (global) {
  'use strict';

  const F = (n, t, d, c) => ({ n, t, d, c: c || 'provavel' });

  // Prefixo comum à maioria dos arquivos
  const CAB = [
    F('registro', 'txt', 'Código do tipo de registro (identifica o leiaute)', 'certeza'),
    F('municipio', 'txt', 'Código do município no TCE-CE', 'certeza'),
    F('exercicio', 'txt', 'Exercício orçamentário (AAAA00)', 'certeza'),
    F('orgao', 'txt', 'Código do órgão', 'certeza'),
    F('unidade', 'txt', 'Código da unidade orçamentária', 'certeza'),
  ];
  const CAB3 = CAB.slice(0, 3);

  const generic = (from, to, prefix) => {
    const out = [];
    for (let i = from; i <= to; i++) out.push(F((prefix || 'campo') + String(i).padStart(2, '0'), 'txt', 'Campo não identificado', 'chute'));
    return out;
  };

  const LAYOUTS = {
    /* ------------------------------------------------------------ DESPESA (.DCD) */
    NE: {
      registro: '601', grupo: 'DCD', nome: 'Nota de Empenho', confianca: 'certeza',
      descricao: 'Empenhos emitidos na competência. Chave: orgao + unidade + numero_empenho (+ data_empenho).',
      chave: ['orgao', 'unidade', 'numero_empenho', 'data_empenho'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho (DDMMSSSS)', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('funcao', 'txt', 'Função', 'certeza'),
        F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'),
        F('tipo_acao', 'txt', 'Tipo de ação (1=projeto, 2=atividade, 0=op. especial)', 'provavel'),
        F('acao', 'txt', 'Ação (projeto/atividade)', 'certeza'),
        F('subacao', 'txt', 'Subação / detalhamento da ação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa (8 dígitos)', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte: 1=exercício corrente, 2=exercícios anteriores', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte/destinação de recursos (9 dígitos). Fonte completa = exercicio_fonte || fonte_recurso', 'certeza'),
        F('campo18', 'txt', 'Campo vazio na amostra', 'chute'),
        F('tipo_empenho', 'txt', 'Tipo: O=ordinário, G=global, E=estimativo', 'certeza'),
        F('historico', 'txt', 'Histórico / objeto do empenho', 'certeza'),
        F('valor_empenho', 'num', 'Valor do empenho (= valor_22 + valor_23 em 100% da amostra)', 'provavel'),
        F('valor_22', 'num', 'Parcela do empenho - coincide com a liquidação do mês na maior parte da amostra', 'chute'),
        F('valor_23', 'num', 'Parcela complementar (valor_empenho - valor_22)', 'chute'),
        F('cpf_24', 'txt', 'CPF (possivelmente do responsável/fiscal do contrato)', 'chute'),
        F('numero_contrato', 'txt', 'Número do contrato', 'provavel'),
        F('data_contrato', 'dat', 'Data do contrato', 'provavel'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'provavel'),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('tipo_licitacao', 'txt', 'Código de modalidade/situação (F, N, D, R)', 'chute'),
        F('tipo_credor', 'txt', 'Tipo de credor (1=PJ, 2=PF, 6/7=folha de pagamento)', 'provavel'),
        F('cpf_cnpj_credor', 'txt', 'CPF/CNPJ do credor', 'certeza'),
        F('nome_credor', 'txt', 'Nome do credor', 'certeza'),
        F('endereco_credor', 'txt', 'Endereço do credor', 'certeza'),
        F('telefone_credor', 'txt', 'Telefone do credor', 'provavel'),
        F('cep_credor', 'txt', 'CEP do credor', 'certeza'),
        F('cidade_credor', 'txt', 'Cidade do credor', 'certeza'),
        F('uf_credor', 'txt', 'UF do credor', 'certeza'),
        F('data_38', 'dat', 'Data não identificada', 'chute'),
        F('campo39', 'txt', 'Código não identificado (O/S)', 'chute'),
        F('campo40', 'txt', 'Código não identificado', 'chute'),
        F('cpf_ordenador', 'txt', 'CPF do ordenador de despesa (coincide com cpf_ordenador da LQ)', 'provavel'),
        F('data_42', 'dat', 'Data não identificada (convênio/termo?)', 'chute'),
        F('campo43', 'txt', 'Referência não identificada (ex.: "02/2021 - 02")', 'chute'),
        F('campo44', 'txt', 'Código não identificado (ex.: "TC")', 'chute'),
        F('campo45', 'txt', 'Campo final ("0000")', 'chute'),
      ],
    },
    LQ: {
      registro: '612', grupo: 'DCD', nome: 'Liquidação da Despesa', confianca: 'certeza',
      descricao: 'Liquidações do mês. Chave: orgao + unidade + numero_empenho + numero_liquidacao.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'data_empenho', 'numero_liquidacao'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('data_liquidacao', 'dat', 'Data da liquidação', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('cpf_ordenador', 'txt', 'CPF do ordenador de despesa', 'provavel'),
        F('nome_ordenador', 'txt', 'Nome do ordenador de despesa', 'provavel'),
        F('numero_liquidacao', 'txt', 'Sequencial da liquidação dentro do empenho ("Sub")', 'certeza'),
        F('valor_liquidacao', 'num', 'Valor liquidado', 'certeza'),
        F('competencia_folha', 'cmp', 'Competência da folha de pagamento (0 quando não é folha)', 'provavel'),
        F('tipo_folha', 'txt', 'Tipo da folha (AN, AD, AC); vazio quando não é folha', 'provavel'),
        F('data_folha', 'dat', 'Data da folha (0 quando não é folha)', 'provavel'),
        F('valor_folha', 'num', 'Valor da folha', 'provavel'),
      ],
    },
    EL: {
      registro: '610', grupo: 'DCD', nome: 'Estorno de Liquidação', confianca: 'certeza',
      descricao: 'Estornos de liquidação. Casa com LQ por orgao + unidade + numero_empenho + data_liquidacao.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'data_liquidacao'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('data_liquidacao', 'dat', 'Data da liquidação estornada', 'certeza'),
        F('data_estorno', 'dat', 'Data do estorno', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('nome_ordenador', 'txt', 'Nome do ordenador de despesa', 'provavel'),
        F('motivo', 'txt', 'Motivo / histórico do estorno', 'certeza'),
      ],
    },
    EG: {
      registro: '611', grupo: 'DCD', nome: 'Estorno de Pagamento', confianca: 'provavel',
      descricao: 'Estornos de pagamento (referencia empenho, liquidação e pagamento).',
      chave: ['orgao', 'unidade', 'numero_empenho', 'numero_liquidacao', 'numero_pagamento'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('numero_liquidacao', 'txt', 'Sequencial da liquidação', 'provavel'),
        F('numero_pagamento', 'txt', 'Número do pagamento estornado', 'provavel'),
        F('data_estorno', 'dat', 'Data do estorno', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('nome_ordenador', 'txt', 'Nome do ordenador', 'provavel'),
        F('motivo', 'txt', 'Motivo do estorno', 'certeza'),
      ],
    },
    AE: {
      registro: '606', grupo: 'DCD', nome: 'Anulação de Empenho', confianca: 'provavel',
      descricao: 'Anulações (totais ou parciais) de empenho.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'data_empenho'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho anulado', 'certeza'),
        F('numero_anulacao', 'txt', 'Número da nota de anulação', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('data_anulacao', 'dat', 'Data da anulação', 'provavel'),
        F('tipo_anulacao', 'txt', 'Tipo (P = parcial?)', 'chute'),
        F('motivo', 'txt', 'Motivo da anulação', 'certeza'),
        F('saldo_apos', 'num', 'Saldo do empenho após a anulação (= saldo_anterior - valor_anulacao)', 'provavel'),
        F('valor_anulacao', 'num', 'Valor anulado', 'provavel'),
        F('saldo_anterior', 'num', 'Saldo do empenho antes da anulação', 'provavel'),
      ],
    },
    NP: {
      registro: '604', grupo: 'DCD', nome: 'Nota de Pagamento', confianca: 'provavel',
      descricao: 'Pagamentos (ordens de pagamento) do mês.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'numero_liquidacao', 'numero_pagamento'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('numero_liquidacao', 'txt', 'Sequencial da liquidação paga', 'provavel'),
        F('numero_pagamento', 'txt', 'Número do pagamento', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('numero_documento', 'txt', 'Número do documento (repete numero_pagamento na amostra)', 'chute'),
        F('data_pagamento', 'dat', 'Data do pagamento', 'provavel'),
        F('valor_pago', 'num', 'Valor pago', 'provavel'),
        F('valor_retencoes', 'num', 'Valor retido/deduzido', 'chute'),
        F('cpf_responsavel', 'txt', 'CPF do responsável pelo pagamento (tesoureiro)', 'chute'),
        F('nome_responsavel', 'txt', 'Nome do responsável pelo pagamento', 'chute'),
      ],
    },
    CP: {
      registro: '605', grupo: 'DCD', nome: 'Pagamento - Conta Bancária', confianca: 'provavel',
      descricao: 'Detalhe bancário dos pagamentos (banco, agência, conta, documento).',
      chave: ['orgao', 'unidade', 'numero_empenho', 'numero_liquidacao', 'numero_pagamento'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('numero_liquidacao', 'txt', 'Sequencial da liquidação', 'provavel'),
        F('numero_pagamento', 'txt', 'Número do pagamento', 'provavel'),
        F('banco', 'txt', 'Código do banco', 'certeza'),
        F('agencia', 'txt', 'Agência', 'certeza'),
        F('conta', 'txt', 'Conta bancária', 'certeza'),
        F('numero_documento_bancario', 'txt', 'Número do documento bancário (OB/cheque/transferência)', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('data_pagamento', 'dat', 'Data do pagamento', 'provavel'),
        F('valor', 'num', 'Valor do documento', 'provavel'),
        F('tipo_documento', 'txt', 'Tipo do documento bancário (código)', 'chute'),
      ],
    },
    DP: {
      registro: '609', grupo: 'DCD', nome: 'Pagamento - Retenções/Consignações', confianca: 'chute',
      descricao: 'Detalhe do pagamento por conta extraorçamentária (retenções). O código casa com o campo conta_extra de TX/DX/XD.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'numero_liquidacao', 'numero_pagamento'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('numero_liquidacao', 'txt', 'Sequencial da liquidação', 'provavel'),
        F('numero_pagamento', 'txt', 'Número do pagamento', 'provavel'),
        F('conta_extra', 'txt', 'Código da conta extraorçamentária (retenção/consignação)', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('valor', 'num', 'Valor', 'provavel'),
        F('tipo', 'txt', 'Código de tipo (E)', 'chute'),
      ],
    },
    PF: {
      registro: '613', grupo: 'DCD', nome: 'Pagamento de Folha', confianca: 'provavel',
      descricao: 'Pagamentos vinculados a folhas de pagamento.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'numero_liquidacao', 'numero_pagamento'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('numero_liquidacao', 'txt', 'Sequencial da liquidação', 'provavel'),
        F('numero_pagamento', 'txt', 'Número do pagamento', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('tipo_folha', 'txt', 'Tipo da folha (AN, AD, AC)', 'provavel'),
        F('data_folha', 'dat', 'Data da folha', 'provavel'),
        F('competencia_folha', 'cmp', 'Competência da folha', 'provavel'),
        F('valor', 'num', 'Valor pago', 'provavel'),
      ],
    },
    NF: {
      registro: '602', grupo: 'DCD', nome: 'Nota Fiscal / Documento da Liquidação', confianca: 'chute',
      descricao: 'Documentos fiscais vinculados às liquidações.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'data_empenho'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('data_liquidacao', 'dat', 'Data da liquidação', 'provavel'),
        F('tipo_documento', 'txt', 'Tipo do documento (S = serviço?)', 'chute'),
        F('numero_documento', 'txt', 'Número da nota fiscal / documento', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        ...generic(12, 15),
        F('data_emissao', 'dat', 'Data de emissão do documento', 'chute'),
        F('serie_ou_numero2', 'txt', 'Série / número secundário', 'chute'),
        F('uf_documento', 'txt', 'UF de emissão', 'chute'),
        F('data_19', 'dat', 'Data não identificada', 'chute'),
        F('valor_documento', 'num', 'Valor do documento', 'provavel'),
        F('valor_21', 'num', 'Valor não identificado', 'chute'),
        F('valor_22', 'num', 'Valor não identificado', 'chute'),
        F('aliquota', 'num', 'Alíquota (%)', 'chute'),
        F('base_calculo', 'num', 'Base de cálculo', 'chute'),
        ...generic(25, 27),
        F('chave_acesso', 'txt', 'Chave/código de verificação do documento', 'chute'),
        F('cnpj_emitente', 'txt', 'CPF/CNPJ do emitente', 'provavel'),
      ],
    },
    IF: {
      registro: '603', grupo: 'DCD', nome: 'Itens da Nota Fiscal / Liquidação', confianca: 'provavel',
      descricao: 'Itens (descrição, quantidade, unitário) dos documentos liquidados.',
      chave: ['orgao', 'unidade', 'numero_empenho', 'data_empenho'],
      campos: [...CAB,
        F('data_empenho', 'dat', 'Data de emissão do empenho', 'certeza'),
        F('numero_empenho', 'txt', 'Número do empenho', 'certeza'),
        F('data_liquidacao', 'dat', 'Data da liquidação', 'provavel'),
        F('tipo_documento', 'txt', 'Tipo do documento', 'chute'),
        F('numero_documento', 'txt', 'Número do documento', 'provavel'),
        F('item', 'txt', 'Sequencial do item', 'provavel'),
        F('descricao', 'txt', 'Descrição do item', 'certeza'),
        F('unidade_medida', 'txt', 'Unidade de medida', 'certeza'),
        F('quantidade', 'num', 'Quantidade', 'certeza'),
        F('valor_unitario', 'num', 'Valor unitário', 'certeza'),
        F('valor_total', 'num', 'Valor total do item', 'certeza'),
        F('campo17', 'txt', 'Campo final', 'chute'),
      ],
    },
    EF: {
      registro: '607', grupo: 'DCD', nome: 'Transferência Financeira entre Contas', confianca: 'provavel',
      descricao: 'Movimentações entre contas bancárias.',
      campos: [...CAB3.slice(0, 2),
        F('data', 'dat', 'Data da transferência', 'provavel'),
        F('sequencial', 'txt', 'Sequencial', 'chute'),
        F('tipo', 'txt', 'Tipo (T)', 'chute'),
        F('banco_origem', 'txt', 'Banco de origem', 'provavel'),
        F('agencia_origem', 'txt', 'Agência de origem', 'provavel'),
        F('conta_origem', 'txt', 'Conta de origem', 'provavel'),
        F('documento', 'txt', 'Documento', 'chute'),
        F('banco_destino', 'txt', 'Banco de destino', 'provavel'),
        F('agencia_destino', 'txt', 'Agência de destino', 'provavel'),
        F('conta_destino', 'txt', 'Conta de destino', 'provavel'),
        F('valor', 'num', 'Valor', 'certeza'),
        F('historico', 'txt', 'Histórico', 'certeza'),
        F('tipo_documento', 'txt', 'Tipo de documento', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    XD: {
      registro: '614', grupo: 'DCD', nome: 'Pagamento Extraorçamentário', confianca: 'chute',
      descricao: 'Pagamentos de contas extraorçamentárias (consignações, retenções) por conta bancária.',
      campos: [...CAB,
        F('conta_extra', 'txt', 'Código da conta extraorçamentária', 'chute'),
        F('banco', 'txt', 'Banco', 'provavel'),
        F('agencia', 'txt', 'Agência', 'provavel'),
        F('conta', 'txt', 'Conta bancária', 'provavel'),
        F('numero', 'txt', 'Número do lançamento', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('numero_documento', 'txt', 'Número do documento', 'chute'),
        F('data', 'dat', 'Data do pagamento', 'provavel'),
        F('valor', 'num', 'Valor', 'provavel'),
        F('valor_15', 'num', 'Valor não identificado', 'chute'),
        F('tipo_documento', 'txt', 'Tipo de documento', 'chute'),
        F('nome_credor', 'txt', 'Nome do beneficiário', 'provavel'),
        F('competencia_referencia', 'cmp', 'Competência de referência', 'chute'),
        F('valor_19', 'num', 'Valor não identificado', 'chute'),
        F('valor_20', 'num', 'Valor não identificado', 'chute'),
      ],
    },
    /* ------------------------------------------------------------ RECEITA (.DCR) */
    TR: {
      registro: '401', grupo: 'DCR', nome: 'Receita Orçamentária (lançamentos)', confianca: 'provavel',
      descricao: 'Lançamentos de arrecadação da receita orçamentária.',
      campos: [...CAB,
        F('conta_receita', 'txt', 'Conta de receita (natureza)', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte (1/2)', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('numero_lancamento', 'txt', 'Número do lançamento', 'provavel'),
        F('data', 'dat', 'Data do lançamento', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('valor', 'num', 'Valor arrecadado', 'certeza'),
        F('historico', 'txt', 'Histórico', 'certeza'),
        F('tipo_credor', 'txt', 'Tipo de pessoa (1=PJ, 2=PF)', 'provavel'),
        F('cpf_cnpj', 'txt', 'CPF/CNPJ do depositante', 'provavel'),
        F('nome', 'txt', 'Nome do depositante', 'provavel'),
        F('banco', 'txt', 'Banco', 'provavel'),
        F('agencia', 'txt', 'Agência', 'provavel'),
        F('conta', 'txt', 'Conta bancária', 'provavel'),
        F('numero_documento', 'txt', 'Documento bancário', 'chute'),
        F('data_documento', 'dat', 'Data do documento', 'chute'),
        F('tipo_documento', 'txt', 'Tipo de documento', 'chute'),
        F('campo23', 'txt', 'Campo final', 'chute'),
      ],
    },
    AT: {
      registro: '402', grupo: 'DCR', nome: 'Anulação de Receita Orçamentária', confianca: 'provavel',
      campos: [...CAB,
        F('conta_receita', 'txt', 'Conta de receita', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('numero_lancamento', 'txt', 'Lançamento anulado', 'provavel'),
        F('data_lancamento', 'dat', 'Data do lançamento original', 'provavel'),
        F('data_anulacao', 'dat', 'Data da anulação', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('tipo', 'txt', 'Tipo (T)', 'chute'),
        F('valor', 'num', 'Valor anulado', 'certeza'),
        F('motivo', 'txt', 'Motivo', 'certeza'),
        F('campo16', 'txt', 'Campo final', 'chute'),
      ],
    },
    TX: {
      registro: '403', grupo: 'DCR', nome: 'Receita Extraorçamentária (lançamentos)', confianca: 'chute',
      descricao: 'Ingressos extraorçamentários (retenções/consignações) - o código da conta casa com DP.conta_extra.',
      campos: [...CAB,
        F('conta_extra', 'txt', 'Código da conta extraorçamentária', 'chute'),
        F('numero_lancamento', 'txt', 'Número do lançamento', 'provavel'),
        F('data', 'dat', 'Data', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('valor', 'num', 'Valor', 'certeza'),
        F('historico', 'txt', 'Histórico', 'certeza'),
        F('tipo_credor', 'txt', 'Tipo de pessoa', 'chute'),
        F('cpf_cnpj_ou_tipo', 'txt', 'CPF/CNPJ ou descrição do tipo', 'chute'),
        F('nome', 'txt', 'Nome', 'provavel'),
        F('banco', 'txt', 'Banco', 'provavel'),
        F('agencia', 'txt', 'Agência', 'provavel'),
        F('conta', 'txt', 'Conta bancária', 'provavel'),
        F('numero_documento', 'txt', 'Documento', 'chute'),
        F('data_documento', 'dat', 'Data do documento', 'chute'),
        F('tipo_documento', 'txt', 'Tipo de documento', 'chute'),
      ],
    },
    AX: {
      registro: '404', grupo: 'DCR', nome: 'Anulação de Receita Extraorçamentária', confianca: 'provavel',
      campos: [...CAB,
        F('conta_extra', 'txt', 'Conta extraorçamentária', 'chute'),
        F('numero_lancamento', 'txt', 'Lançamento anulado', 'provavel'),
        F('data_lancamento', 'dat', 'Data do lançamento original', 'provavel'),
        F('data_anulacao', 'dat', 'Data da anulação', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('tipo', 'txt', 'Tipo (T)', 'chute'),
        F('valor', 'num', 'Valor anulado', 'certeza'),
        F('motivo', 'txt', 'Motivo', 'certeza'),
      ],
    },
    /* ------------------------------------------------------------ BALANCETES (.BAL) */
    BD: {
      registro: '302', grupo: 'BAL', nome: 'Balancete da Despesa Orçamentária', confianca: 'provavel',
      descricao: 'Saldos por dotação (função ... elemento, fonte). As colunas de valor não foram identificadas individualmente.',
      campos: [...CAB,
        F('funcao', 'txt', 'Função', 'certeza'),
        F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'),
        F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'),
        F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza_saldo', 'txt', 'Natureza (D/C)', 'chute'),
        ...generic(17, 43, 'valor_'),
      ],
    },
    BA: {
      registro: '308', grupo: 'BAL', nome: 'Balancete Contábil Analítico (por dotação)', confianca: 'provavel',
      campos: [...CAB3,
        F('tipo', 'txt', 'Tipo de registro', 'chute'),
        F('conta_contabil', 'txt', 'Conta contábil (PCASP)', 'certeza'),
        F('orgao', 'txt', 'Órgão', 'certeza'),
        F('unidade', 'txt', 'Unidade', 'certeza'),
        F('funcao', 'txt', 'Função', 'certeza'),
        F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'),
        F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'),
        F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('campo17', 'txt', 'Campo não identificado', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza_saldo_anterior', 'txt', 'D/C do saldo anterior', 'provavel'),
        F('saldo_anterior', 'num', 'Saldo anterior', 'provavel'),
        F('debitos', 'num', 'Débitos do mês', 'provavel'),
        F('creditos', 'num', 'Créditos do mês', 'provavel'),
        F('natureza_saldo_atual', 'txt', 'D/C do saldo atual', 'provavel'),
        F('saldo_atual', 'num', 'Saldo atual', 'provavel'),
        F('campo25', 'txt', 'Campo final', 'chute'),
      ],
    },
    BB: {
      registro: '306', grupo: 'BAL', nome: 'Balancete Contábil - Contas Bancárias', confianca: 'provavel',
      campos: [...CAB3,
        F('tipo', 'txt', 'Tipo de registro', 'chute'),
        F('conta_contabil', 'txt', 'Conta contábil', 'certeza'),
        F('banco', 'txt', 'Banco', 'certeza'),
        F('agencia', 'txt', 'Agência', 'certeza'),
        F('conta', 'txt', 'Conta bancária', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza_saldo_anterior', 'txt', 'D/C', 'provavel'),
        F('saldo_anterior', 'num', 'Saldo anterior', 'provavel'),
        F('debitos', 'num', 'Débitos', 'provavel'),
        F('creditos', 'num', 'Créditos', 'provavel'),
        F('natureza_saldo_atual', 'txt', 'D/C', 'provavel'),
        F('saldo_atual', 'num', 'Saldo atual', 'provavel'),
      ],
    },
    BC: {
      registro: '305', grupo: 'BAL', nome: 'Balancete Contábil (contas sem detalhamento)', confianca: 'chute',
      campos: [...CAB3,
        F('tipo', 'txt', 'Tipo de registro', 'chute'),
        F('conta_contabil', 'txt', 'Conta contábil', 'certeza'),
        F('atributo', 'txt', 'Atributo (F/P/N)', 'chute'),
        F('campo07', 'txt', 'Campo não identificado', 'chute'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'chute'),
        F('campo09', 'txt', 'Campo não identificado', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('campo11', 'txt', 'Campo não identificado', 'chute'),
        F('campo12', 'txt', 'Campo não identificado', 'chute'),
        F('natureza_saldo_anterior', 'txt', 'D/C', 'provavel'),
        F('saldo_anterior', 'num', 'Saldo anterior', 'provavel'),
        F('debitos', 'num', 'Débitos', 'provavel'),
        F('creditos', 'num', 'Créditos', 'provavel'),
        F('natureza_saldo_atual', 'txt', 'D/C', 'provavel'),
        F('saldo_atual', 'num', 'Saldo atual', 'provavel'),
        ...generic(19, 22, 'valor_'),
      ],
    },
    BE: {
      registro: '307', grupo: 'BAL', nome: 'Balancete Contábil - Receita por Conta', confianca: 'chute',
      campos: [...CAB3,
        F('tipo', 'txt', 'Tipo de registro', 'chute'),
        F('conta_contabil', 'txt', 'Conta contábil', 'certeza'),
        F('conta_receita', 'txt', 'Conta de receita', 'provavel'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('campo09', 'txt', 'Campo não identificado', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza_saldo_anterior', 'txt', 'D/C', 'provavel'),
        F('saldo_anterior', 'num', 'Saldo anterior', 'provavel'),
        F('debitos', 'num', 'Débitos', 'provavel'),
        F('creditos', 'num', 'Créditos', 'provavel'),
        F('natureza_saldo_atual', 'txt', 'D/C', 'provavel'),
        F('saldo_atual', 'num', 'Saldo atual', 'provavel'),
      ],
    },
    BR: {
      registro: '301', grupo: 'BAL', nome: 'Balancete da Receita Orçamentária', confianca: 'provavel',
      campos: [...CAB,
        F('conta_receita', 'txt', 'Conta de receita', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza', 'txt', 'D/C', 'chute'),
        ...generic(11, 15, 'valor_'),
      ],
    },
    DX: {
      registro: '304', grupo: 'BAL', nome: 'Balancete da Despesa Extraorçamentária', confianca: 'provavel',
      campos: [...CAB,
        F('conta_extra', 'txt', 'Conta extraorçamentária', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza', 'txt', 'D/C', 'chute'),
        ...generic(9, 12, 'valor_'),
      ],
    },
    RX: {
      registro: '303', grupo: 'BAL', nome: 'Balancete da Receita Extraorçamentária', confianca: 'provavel',
      campos: [...CAB,
        F('conta_extra', 'txt', 'Conta extraorçamentária', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('natureza', 'txt', 'D/C', 'chute'),
        ...generic(9, 12, 'valor_'),
      ],
    },
    /* ------------------------------------------------------------ ORÇAMENTO (.ORC) */
    EP: {
      registro: '204', grupo: 'ORC', nome: 'Orçamento - Dotações da Despesa', confianca: 'provavel',
      campos: [...CAB,
        F('funcao', 'txt', 'Função', 'certeza'), F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'), F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'), F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('valor', 'num', 'Valor da dotação', 'provavel'),
      ],
    },
    PA: {
      registro: '203', grupo: 'ORC', nome: 'Orçamento - Programas/Ações', confianca: 'provavel',
      campos: [...CAB,
        F('funcao', 'txt', 'Função', 'certeza'), F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'), F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'), F('subacao', 'txt', 'Subação', 'chute'),
        F('tipo', 'txt', 'Tipo (F)', 'chute'),
        F('nome_acao', 'txt', 'Nome da ação', 'provavel'),
        F('descricao_acao', 'txt', 'Descrição da ação', 'provavel'),
        F('valor', 'num', 'Valor', 'provavel'),
      ],
    },
    RE: {
      registro: '201', grupo: 'ORC', nome: 'Orçamento - Previsão da Receita', confianca: 'provavel',
      campos: [...CAB,
        F('conta_receita', 'txt', 'Conta de receita', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('descricao', 'txt', 'Descrição da receita', 'certeza'),
        F('valor', 'num', 'Valor previsto', 'provavel'),
      ],
    },
    /* ------------------------------------------------------------ CRÉDITOS ADICIONAIS (.CRD) */
    CA: {
      registro: '701', grupo: 'CRD', nome: 'Créditos Adicionais', confianca: 'provavel',
      campos: [...CAB3,
        F('data', 'dat', 'Data', 'provavel'),
        F('tipo_credito', 'txt', 'Tipo de crédito/alteração', 'chute'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('funcao', 'txt', 'Função', 'certeza'), F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'), F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'), F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('lei', 'txt', 'Lei autorizativa', 'provavel'),
        F('decreto', 'txt', 'Decreto', 'provavel'),
        F('campo20', 'txt', 'Campo não identificado', 'chute'),
        F('campo21', 'txt', 'Campo não identificado', 'chute'),
        ...generic(22, 25, 'valor_'),
      ],
    },
    FA: {
      registro: '702', grupo: 'CRD', nome: 'Créditos Adicionais - Fonte (Anulação de dotação)', confianca: 'chute',
      campos: [...CAB3,
        F('data', 'dat', 'Data', 'provavel'),
        F('tipo_credito', 'txt', 'Tipo', 'chute'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('funcao', 'txt', 'Função', 'certeza'), F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'), F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'), F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('valor', 'num', 'Valor', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    MF: {
      registro: '705', grupo: 'CRD', nome: 'Movimentação de Fonte / Remanejamento', confianca: 'chute',
      campos: [...CAB3,
        F('data', 'dat', 'Data', 'provavel'),
        F('tipo_credito', 'txt', 'Tipo', 'chute'),
        F('campo06', 'txt', 'Campo não identificado', 'chute'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('funcao', 'txt', 'Função', 'certeza'), F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'), F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'), F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte_origem', 'txt', 'Identificador da fonte de origem', 'chute'),
        F('fonte_origem', 'txt', 'Fonte de origem', 'chute'),
        F('exercicio_fonte_destino', 'txt', 'Identificador da fonte de destino', 'chute'),
        F('fonte_destino', 'txt', 'Fonte de destino', 'chute'),
        F('valor', 'num', 'Valor', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    /* ------------------------------------------------------------ LICITAÇÕES E CONTRATOS (.LCO) */
    LI: {
      registro: '501', grupo: 'LCO', nome: 'Licitações', confianca: 'provavel',
      chave: ['numero_licitacao'],
      campos: [...CAB3.slice(0, 2),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'certeza'),
        F('modalidade', 'txt', 'Modalidade (código)', 'provavel'),
        F('objeto', 'txt', 'Objeto', 'certeza'),
        F('valor_estimado', 'num', 'Valor estimado', 'provavel'),
        F('cpf_responsavel', 'txt', 'CPF do responsável (pregoeiro/presidente)', 'chute'),
        F('nome_responsavel', 'txt', 'Nome do responsável', 'chute'),
        F('cpf_ordenador', 'txt', 'CPF do ordenador/gestor', 'chute'),
        F('data_10', 'dat', 'Data não identificada (nomeação?)', 'chute'),
        F('campo12', 'txt', 'Campo não identificado', 'chute'),
        F('cpf_13', 'txt', 'CPF não identificado', 'chute'),
        F('nome_14', 'txt', 'Nome não identificado', 'chute'),
        F('data_abertura', 'dat', 'Data de abertura', 'chute'),
        F('hora_abertura', 'txt', 'Hora de abertura', 'chute'),
        F('data_publicacao', 'dat', 'Data de publicação', 'chute'),
        F('campo18', 'txt', 'Campo não identificado', 'chute'),
        F('campo19', 'txt', 'Campo não identificado', 'chute'),
        F('valor_20', 'num', 'Valor', 'chute'),
        ...generic(21, 24),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    LT: {
      registro: '505', grupo: 'LCO', nome: 'Licitantes', confianca: 'provavel',
      chave: ['numero_licitacao'],
      campos: [...CAB3.slice(0, 2),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'certeza'),
        F('tipo_pessoa', 'txt', 'Tipo (1=PJ, 2=PF)', 'provavel'),
        F('cpf_cnpj', 'txt', 'CPF/CNPJ do licitante', 'certeza'),
        F('nome', 'txt', 'Nome do licitante', 'certeza'),
        F('endereco', 'txt', 'Endereço', 'certeza'), F('telefone', 'txt', 'Telefone', 'provavel'),
        F('cep', 'txt', 'CEP', 'certeza'), F('cidade', 'txt', 'Cidade', 'certeza'), F('uf', 'txt', 'UF', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    TL: {
      registro: '506', grupo: 'LCO', nome: 'Itens da Licitação', confianca: 'provavel',
      chave: ['numero_licitacao'],
      campos: [...CAB3.slice(0, 2),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'certeza'),
        F('item', 'txt', 'Número do item', 'provavel'),
        F('descricao', 'txt', 'Descrição do item', 'certeza'),
        F('unidade_medida', 'txt', 'Unidade', 'certeza'),
        F('quantidade', 'num', 'Quantidade', 'certeza'),
        F('valor_unitario', 'num', 'Valor unitário', 'certeza'),
        F('valor_total', 'num', 'Valor total', 'certeza'),
        F('tipo_pessoa_vencedor', 'txt', 'Tipo do vencedor', 'chute'),
        F('cpf_cnpj_vencedor', 'txt', 'CPF/CNPJ do vencedor', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    PE: {
      registro: '502', grupo: 'LCO', nome: 'Publicações da Licitação', confianca: 'provavel',
      chave: ['numero_licitacao'],
      campos: [...CAB3.slice(0, 2),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'certeza'),
        F('tipo_publicacao', 'txt', 'Tipo de publicação', 'chute'),
        F('veiculo_codigo', 'txt', 'Código do veículo', 'chute'),
        F('veiculo', 'txt', 'Veículo de publicação', 'certeza'),
        F('data_publicacao', 'dat', 'Data da publicação', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    DL: {
      registro: '507', grupo: 'LCO', nome: 'Dotações da Licitação', confianca: 'provavel',
      chave: ['numero_licitacao'],
      campos: [...CAB3.slice(0, 2),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'certeza'),
        F('exercicio', 'txt', 'Exercício', 'certeza'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('funcao', 'txt', 'Função', 'certeza'), F('subfuncao', 'txt', 'Subfunção', 'certeza'),
        F('programa', 'txt', 'Programa', 'certeza'), F('tipo_acao', 'txt', 'Tipo de ação', 'provavel'),
        F('acao', 'txt', 'Ação', 'certeza'), F('subacao', 'txt', 'Subação', 'chute'),
        F('elemento_despesa', 'txt', 'Natureza da despesa', 'certeza'),
        F('exercicio_fonte', 'txt', 'Identificador da fonte', 'provavel'),
        F('fonte_recurso', 'txt', 'Fonte de recursos', 'certeza'),
        F('valor', 'num', 'Valor', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    CO: {
      registro: '511', grupo: 'LCO', nome: 'Contratos', confianca: 'provavel',
      chave: ['numero_contrato'],
      campos: [...CAB3.slice(0, 2),
        F('cpf_gestor', 'txt', 'CPF do gestor/signatário', 'chute'),
        F('numero_contrato', 'txt', 'Número do contrato', 'certeza'),
        F('data_contrato', 'dat', 'Data do contrato', 'provavel'),
        F('tipo', 'txt', 'Tipo (O)', 'chute'),
        F('campo07', 'txt', 'Código não identificado (AR)', 'chute'),
        F('cpf_08', 'txt', 'CPF não identificado', 'chute'),
        F('numero_licitacao', 'txt', 'Número da licitação', 'provavel'),
        F('data_licitacao', 'dat', 'Data da licitação', 'provavel'),
        F('inicio_vigencia', 'dat', 'Início da vigência', 'provavel'),
        F('fim_vigencia', 'dat', 'Fim da vigência', 'provavel'),
        F('objeto', 'txt', 'Objeto', 'certeza'),
        F('valor', 'num', 'Valor', 'provavel'),
        ...generic(15, 18),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    CT: {
      registro: '513', grupo: 'LCO', nome: 'Contratados', confianca: 'provavel',
      chave: ['numero_contrato'],
      campos: [...CAB3.slice(0, 2),
        F('cpf_gestor', 'txt', 'CPF do gestor/signatário', 'chute'),
        F('numero_contrato', 'txt', 'Número do contrato', 'certeza'),
        F('data_contrato', 'dat', 'Data do contrato', 'provavel'),
        F('tipo_pessoa', 'txt', 'Tipo (1=PJ, 2=PF)', 'provavel'),
        F('cpf_cnpj', 'txt', 'CPF/CNPJ do contratado', 'certeza'),
        F('nome', 'txt', 'Nome do contratado', 'certeza'),
        F('endereco', 'txt', 'Endereço', 'certeza'), F('telefone', 'txt', 'Telefone', 'provavel'),
        F('cep', 'txt', 'CEP', 'certeza'), F('cidade', 'txt', 'Cidade', 'certeza'), F('uf', 'txt', 'UF', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    /* ------------------------------------------------------------ PESSOAL (.CPF) */
    FP: {
      registro: '958', grupo: 'CPF', nome: 'Folha de Pagamento - Resumo', confianca: 'provavel',
      campos: [...CAB,
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('tipo_folha', 'txt', 'Tipo da folha (AN, AD, AC)', 'provavel'),
        F('data_folha', 'dat', 'Data da folha', 'provavel'),
        F('competencia_folha', 'cmp', 'Competência da folha', 'provavel'),
        F('valor_bruto', 'num', 'Valor bruto', 'chute'),
        F('valor_descontos', 'num', 'Descontos', 'chute'),
        ...generic(12, 17, 'valor_'),
        F('valor_18', 'num', 'Valor não identificado', 'chute'),
      ],
    },
    AF: {
      registro: '959', grupo: 'CPF', nome: 'Folha de Pagamento - Analítica (por servidor/verba)', confianca: 'provavel',
      campos: [...CAB,
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('tipo_folha', 'txt', 'Tipo da folha', 'provavel'),
        F('data_folha', 'dat', 'Data da folha', 'provavel'),
        F('cpf_servidor', 'txt', 'CPF do servidor', 'certeza'),
        F('campo10', 'txt', 'Código não identificado (C/T)', 'chute'),
        F('campo11', 'txt', 'Código não identificado (J/H)', 'chute'),
        F('norma', 'txt', 'Lei/norma do vínculo', 'chute'),
        F('codigo_verba', 'txt', 'Código da verba/rubrica', 'provavel'),
        F('valor', 'num', 'Valor da verba', 'certeza'),
        F('tipo_verba', 'txt', 'Tipo (vazio/O)', 'chute'),
        F('competencia_folha', 'cmp', 'Competência da folha', 'provavel'),
        F('campo17', 'txt', 'Campo não identificado', 'chute'),
      ],
    },
    CR: {
      registro: '956', grupo: 'CPF', nome: 'Cargos / Vínculos', confianca: 'chute',
      campos: [...CAB,
        F('cpf_servidor', 'txt', 'CPF do servidor', 'certeza'),
        F('campo07', 'txt', 'Código (C/T)', 'chute'), F('campo08', 'txt', 'Código (J/H)', 'chute'),
        F('norma', 'txt', 'Lei/norma', 'chute'), F('codigo', 'txt', 'Código do cargo/verba', 'chute'),
        F('campo11', 'txt', 'Código (LOM)', 'chute'), F('campo12', 'txt', 'Código (D)', 'chute'),
        F('data_13', 'dat', 'Data', 'chute'), F('data_14', 'dat', 'Data', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    DS: {
      registro: '952', grupo: 'CPF', nome: 'Desligamentos / Afastamentos', confianca: 'chute',
      campos: [...CAB,
        F('cpf_servidor', 'txt', 'CPF do servidor', 'certeza'),
        F('campo07', 'txt', 'Código (C/T)', 'chute'), F('campo08', 'txt', 'Código (J/H)', 'chute'),
        F('norma', 'txt', 'Lei/norma', 'chute'), F('ato', 'txt', 'Ato', 'chute'),
        F('campo11', 'txt', 'Código', 'chute'), F('campo12', 'txt', 'Código', 'chute'),
        F('data_13', 'dat', 'Data', 'chute'), F('data_14', 'dat', 'Data', 'chute'),
        ...generic(15, 18),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    AP: {
      registro: '951', grupo: 'CPF', nome: 'Admissões de Pessoal', confianca: 'chute',
      campos: [...CAB,
        F('cpf_servidor', 'txt', 'CPF do servidor', 'certeza'),
        F('campo07', 'txt', 'Código (C/T)', 'chute'), F('campo08', 'txt', 'Código (J/H)', 'chute'),
        F('norma', 'txt', 'Lei/norma', 'chute'), F('campo10', 'txt', 'Código', 'chute'),
        F('data_admissao', 'dat', 'Data de admissão', 'chute'),
        F('campo12', 'txt', 'Código', 'chute'), F('ato', 'txt', 'Ato/edital', 'chute'),
        F('data_14', 'dat', 'Data', 'chute'), F('data_15', 'dat', 'Data', 'chute'), F('data_16', 'dat', 'Data', 'chute'),
        F('matricula', 'txt', 'Matrícula', 'chute'),
        ...generic(18, 24),
        F('pis_pasep', 'txt', 'PIS/PASEP (11 dígitos)', 'chute'),
        F('rg', 'txt', 'RG', 'chute'), F('orgao_rg', 'txt', 'Órgão emissor do RG', 'chute'),
        F('titulo_eleitor', 'txt', 'Título de eleitor (13 dígitos)', 'chute'),
        ...generic(29, 31),
        F('nome', 'txt', 'Nome do servidor', 'provavel'),
        F('nome_mae', 'txt', 'Nome da mãe', 'chute'), F('nome_pai', 'txt', 'Nome do pai', 'chute'),
        F('endereco', 'txt', 'Endereço', 'provavel'), F('telefone', 'txt', 'Telefone', 'chute'),
        F('data_nascimento', 'dat', 'Data de nascimento', 'provavel'),
        F('campo38', 'txt', 'Código não identificado', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('cargo', 'txt', 'Cargo', 'provavel'),
      ],
    },
    /* ------------------------------------------------------------ PATRIMÔNIO (.PAT) */
    BO: {
      registro: '981', grupo: 'PAT', nome: 'Bens - Incorporações', confianca: 'chute',
      campos: [...CAB3.slice(0, 2),
        F('numero_bem', 'txt', 'Número do bem (tombamento)', 'provavel'),
        F('data', 'dat', 'Data', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('exercicio', 'txt', 'Exercício', 'certeza'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('cpf_responsavel', 'txt', 'CPF do responsável', 'chute'),
        F('campo10', 'txt', 'Código', 'chute'), F('campo11', 'txt', 'Código', 'chute'),
        F('documento', 'txt', 'Documento/portaria', 'chute'),
      ],
    },
    BN: {
      registro: '983', grupo: 'PAT', nome: 'Bens - Vínculo com Empenho', confianca: 'chute',
      campos: [...CAB3.slice(0, 2),
        F('numero_bem', 'txt', 'Número do bem', 'provavel'),
        F('exercicio', 'txt', 'Exercício', 'certeza'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('data_empenho', 'dat', 'Data do empenho', 'provavel'),
        F('numero_empenho', 'txt', 'Número do empenho', 'provavel'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
      ],
    },
    RP: {
      registro: '984', grupo: 'PAT', nome: 'Bens - Depreciação / Reavaliação', confianca: 'chute',
      campos: [...CAB3.slice(0, 2),
        F('numero_bem', 'txt', 'Número do bem', 'provavel'),
        F('data', 'dat', 'Data', 'provavel'),
        F('tipo', 'txt', 'Tipo', 'chute'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('exercicio', 'txt', 'Exercício', 'certeza'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('cpf_responsavel', 'txt', 'CPF do responsável', 'chute'),
        F('campo11', 'txt', 'Código', 'chute'), F('campo12', 'txt', 'Código', 'chute'),
        F('documento', 'txt', 'Documento', 'chute'),
        F('valor', 'num', 'Valor', 'provavel'),
        F('historico', 'txt', 'Histórico', 'certeza'),
      ],
    },
    /* ------------------------------------------------------------ OBRAS (.OSE) */
    OS: {
      registro: '901', grupo: 'OSE', nome: 'Obras e Serviços de Engenharia', confianca: 'chute',
      campos: [...CAB3.slice(0, 2), F('data', 'dat', 'Data', 'chute'), F('tipo', 'txt', 'Tipo (O/S)', 'chute'),
        F('numero_obra', 'txt', 'Número da obra', 'provavel'), F('exercicio', 'txt', 'Exercício', 'certeza'),
        F('orgao', 'txt', 'Órgão', 'certeza'), F('unidade', 'txt', 'Unidade', 'certeza'),
        F('objeto', 'txt', 'Objeto', 'certeza'), ...generic(10, 12),
        F('valor', 'num', 'Valor', 'chute'), ...generic(14, 32)],
    },
    MO: {
      registro: '902', grupo: 'OSE', nome: 'Medições de Obras', confianca: 'chute',
      campos: [...CAB, F('data_empenho', 'dat', 'Data do empenho', 'provavel'), F('numero_empenho', 'txt', 'Número do empenho', 'provavel'),
        F('data_obra', 'dat', 'Data da obra', 'chute'), F('tipo', 'txt', 'Tipo (O/S)', 'chute'), F('numero_obra', 'txt', 'Número da obra', 'provavel'),
        F('numero_medicao', 'txt', 'Número da medição', 'chute'), F('valor', 'num', 'Valor da medição', 'provavel'),
        F('data_medicao', 'dat', 'Data da medição', 'chute'), ...generic(14, 21), F('competencia', 'cmp', 'Competência da remessa', 'certeza')],
    },
    SO: {
      registro: '903', grupo: 'OSE', nome: 'Situação de Obras', confianca: 'chute',
      campos: [...CAB3.slice(0, 2), F('data_obra', 'dat', 'Data da obra', 'chute'), F('tipo', 'txt', 'Tipo (O/S)', 'chute'),
        F('numero_obra', 'txt', 'Número da obra', 'provavel'), F('data', 'dat', 'Data da situação', 'chute'), F('campo07', 'txt', 'Código', 'chute'),
        F('cpf_responsavel', 'txt', 'CPF do responsável técnico', 'chute'), F('nome_responsavel', 'txt', 'Nome do responsável', 'chute'),
        F('telefone', 'txt', 'Telefone', 'chute'), F('campo11', 'txt', 'Campo', 'chute'), F('situacao', 'txt', 'Situação da obra', 'provavel'),
        ...generic(13, 15)],
    },
    /* ------------------------------------------------------------ OUTROS */
    DA: {
      registro: '805', grupo: 'OUT', nome: 'Diárias', confianca: 'provavel',
      campos: [...CAB, F('cpf_beneficiario', 'txt', 'CPF do beneficiário', 'provavel'), F('numero_ato', 'txt', 'Número do ato/portaria', 'provavel'),
        F('data_ato', 'dat', 'Data do ato', 'provavel'), F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('finalidade', 'txt', 'Finalidade', 'certeza'), F('cidade_destino', 'txt', 'Cidade de destino', 'certeza'), F('uf_destino', 'txt', 'UF de destino', 'certeza'),
        F('data_inicio', 'dat', 'Data de início', 'provavel'), F('data_fim', 'dat', 'Data de fim', 'provavel'),
        F('quantidade_diarias', 'num', 'Quantidade de diárias', 'provavel'), F('valor_unitario', 'num', 'Valor unitário', 'provavel'),
        F('valor_total', 'num', 'Valor total', 'provavel'), F('data_empenho', 'dat', 'Data do empenho', 'provavel'),
        F('numero_empenho', 'txt', 'Número do empenho', 'provavel'), F('numero_liquidacao', 'txt', 'Sequencial da liquidação', 'chute'),
        F('numero_pagamento', 'txt', 'Número do pagamento', 'chute')],
    },
    CB: {
      registro: '106', grupo: 'BAS', nome: 'Cadastro de Contas Bancárias', confianca: 'provavel',
      campos: [...CAB, F('banco', 'txt', 'Banco', 'certeza'), F('agencia', 'txt', 'Agência', 'certeza'), F('conta', 'txt', 'Conta bancária', 'certeza'),
        F('competencia', 'cmp', 'Competência da remessa', 'certeza'), F('data', 'dat', 'Data', 'chute'), F('valor', 'num', 'Valor', 'chute'),
        F('tipo', 'txt', 'Tipo', 'chute'), F('campo13', 'txt', 'Campo', 'chute'), F('campo14', 'txt', 'Campo', 'chute')],
    },
    XC: {
      registro: '107', grupo: 'BAS', nome: 'Cadastro de Contas Extraorçamentárias', confianca: 'chute',
      campos: [...CAB3, F('conta_extra', 'txt', 'Código da conta extraorçamentária', 'chute'), F('competencia', 'cmp', 'Competência da remessa', 'certeza'),
        F('descricao', 'txt', 'Descrição', 'provavel'), F('valor', 'num', 'Valor', 'chute')],
    },
    RC: {
      registro: '999', grupo: 'CTR', nome: 'Registro de Controle / Responsáveis', confianca: 'chute',
      campos: [F('registro', 'txt', 'Código do registro', 'certeza'), F('cpf_gestor', 'txt', 'CPF do gestor', 'provavel'), F('nome_gestor', 'txt', 'Nome do gestor', 'provavel'),
        ...generic(4, 13)],
    },
  };

  // Colunas de metadados acrescentadas a todas as tabelas
  const META = [
    F('_arquivo', 'txt', 'Nome do arquivo de remessa (ex.: LQ202312.DCD)', 'certeza'),
    F('_competencia', 'cmp', 'Competência extraída do nome do arquivo (AAAAMM)', 'certeza'),
    F('_linha', 'num', 'Número da linha no arquivo (1 = primeira linha)', 'certeza'),
    F('_pacote', 'txt', 'Nome do ZIP de origem (vazio se arquivo avulso)', 'certeza'),
  ];

  // Colunas usadas para sugerir chaves de junção
  const JOIN_KEYS = ['orgao', 'unidade', 'numero_empenho', 'data_empenho', 'numero_liquidacao', 'numero_pagamento',
    'data_liquidacao', 'numero_contrato', 'numero_licitacao', 'cpf_cnpj_credor', 'cpf_cnpj', 'cpf_servidor', 'conta_contabil',
    'conta_receita', 'conta_extra', 'banco', 'agencia', 'conta', 'numero_bem', 'numero_obra', 'fonte_recurso', 'elemento_despesa', '_competencia'];

  global.SIM_LAYOUTS = { LAYOUTS, META, JOIN_KEYS };
})(window);
